#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.1.9f1_d5f1b37da199"
#define UNITY_VERSION_FULL_NICE "2019.1.9f1 (d5f1b37da199)"
#define UNITY_VERSION_BLD 14021043
#define UNITY_VERSION_DATE 1561729891
#define UNITY_VERSION_WIN "2019.1.9.14021043"
#define UNITY_VERSION_BRANCH "2019.1/staging"
